package modelo;
// Generated 30/03/2019 01:45:04 PM by Hibernate Tools 4.3.1



/**
 * Comentario generated by hbm2java
 */
public class Comentario  implements java.io.Serializable {


     private int idcomentario;
     private Integer calificacion;
     private String descripcion;
     private String correo;

    public Comentario() {
    }

	
    public Comentario(int idcomentario, String descripcion, String correo) {
        this.idcomentario = idcomentario;
        this.descripcion = descripcion;
        this.correo = correo;
    }
    public Comentario(int idcomentario, Integer calificacion, String descripcion, String correo) {
       this.idcomentario = idcomentario;
       this.calificacion = calificacion;
       this.descripcion = descripcion;
       this.correo = correo;
    }
   
    public int getIdcomentario() {
        return this.idcomentario;
    }
    
    public void setIdcomentario(int idcomentario) {
        this.idcomentario = idcomentario;
    }
    public Integer getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(Integer calificacion) {
        this.calificacion = calificacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }




}


