package modelo;
// Generated 30/03/2019 01:45:04 PM by Hibernate Tools 4.3.1



/**
 * Megusta generated by hbm2java
 */
public class Megusta  implements java.io.Serializable {


     private int idmegusta;
     private Boolean valor;
     private String correo;
     private Integer comentario;

    public Megusta() {
    }

	
    public Megusta(int idmegusta) {
        this.idmegusta = idmegusta;
    }
    public Megusta(int idmegusta, Boolean valor, String correo, Integer comentario) {
       this.idmegusta = idmegusta;
       this.valor = valor;
       this.correo = correo;
       this.comentario = comentario;
    }
   
    public int getIdmegusta() {
        return this.idmegusta;
    }
    
    public void setIdmegusta(int idmegusta) {
        this.idmegusta = idmegusta;
    }
    public Boolean getValor() {
        return this.valor;
    }
    
    public void setValor(Boolean valor) {
        this.valor = valor;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Integer getComentario() {
        return this.comentario;
    }
    
    public void setComentario(Integer comentario) {
        this.comentario = comentario;
    }




}


