package modelo;
// Generated 30/03/2019 01:45:04 PM by Hibernate Tools 4.3.1



/**
 * Tema generated by hbm2java
 */
public class Tema  implements java.io.Serializable {


     private int idtema;
     private String nombretema;
     private String correo;
     private String color;

    public Tema() {
    }

	
    public Tema(int idtema) {
        this.idtema = idtema;
    }
    public Tema(int idtema, String nombretema, String correo, String color) {
       this.idtema = idtema;
       this.nombretema = nombretema;
       this.correo = correo;
       this.color = color;
    }
   
    public int getIdtema() {
        return this.idtema;
    }
    
    public void setIdtema(int idtema) {
        this.idtema = idtema;
    }
    public String getNombretema() {
        return this.nombretema;
    }
    
    public void setNombretema(String nombretema) {
        this.nombretema = nombretema;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }




}


