package modelo;
// Generated 30/03/2019 01:45:04 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String correo;
     private Boolean activo;
     private String nombreusuario;
     private Integer rol;
     private String contrasenia;

    public Usuario() {
    }

	
    public Usuario(String correo) {
        this.correo = correo;
    }
    public Usuario(String correo, Boolean activo, String nombreusuario, Integer rol, String contrasenia) {
       this.correo = correo;
       this.activo = activo;
       this.nombreusuario = nombreusuario;
       this.rol = rol;
       this.contrasenia = contrasenia;
    }
   
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
    public String getNombreusuario() {
        return this.nombreusuario;
    }
    
    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }
    public Integer getRol() {
        return this.rol;
    }
    
    public void setRol(Integer rol) {
        this.rol = rol;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }




}


